Create Best Practices and Error Handling
IntuitDeveloper/intuit-api-docs pull request #6
Opened 2021-01-20 07:38 UTC by irajczi

Adding section where people can troubleshoot and make sure they are doing the best stuff

2021-01-20 18:18 UTC, bcole requested changes
Left some comments, also let's change the filename to something more conventional (lowercase, no spaces, ends in `.md`).

`error-handling-best-practices.md` or anything like that is fine.

2021-01-20 18:18 UTC, bcole commented on docs/graphql-concepts/Best Practices and Error Handling
> +---
```suggestion
---
```
Need to remove beginning space, it breaks rendering

2021-01-20 18:18 UTC, bcole commented on docs/graphql-concepts/Best Practices and Error Handling
> +nav_order: 4
Can you confirm which order you want this file in?  We could make this value `6` to put it at the bottom of the list, if you want.

We already have a `4` (other concepts page), so if you want this to be `4` we should move the other pages to `5` and `6`.  Just let me know where in the sidebar you want this page ordered.

<img width="346" alt="Screen Shot 2021-01-20 at 10 09 23 AM" src="https://user-images.githubusercontent.com/1093919/105216568-96edd600-5b07-11eb-8054-3a6b8615c78f.png">

2021-01-20 18:18 UTC, bcole commented on docs/graphql-concepts/Best Practices and Error Handling
> +#### Using Fragments
Introspection has it's own page in GraphQL concepts.  Fragments and Pagination (just added in your other PR) are in Other Concepts.

Just checking, do we want them here too?  If so, should we at least link from this "one-liner" here to the pages that explain the concepts in more detail?

2021-01-20 18:37 UTC, irajczi commented on docs/graphql-concepts/Best Practices and Error Handling
> +#### Using Fragments
I agree but since this isn't exactly how to do it, I would say that having the reference to use it and understand what the term is for a complete newb would be helpful

2021-01-20 19:34 UTC, irajczi commented on docs/graphql-concepts/Best Practices and Error Handling
> +nav_order: 4
I would say that other should be at the end, didn't realize that number was related to the ordering (I just copied the header)

2021-01-20 19:58 UTC, bcole commented on docs/graphql-concepts/Best Practices and Error Handling
> +nav_order: 4
Sure, let's change it to `6` then
```suggestion
nav_order: 6
```

2021-01-21 00:00 UTC, bcole commented on docs/graphql-concepts/Best Practices and Error Handling
> +#### Using Fragments
Alright, just added a "suggestion" (you should see it below this) to add the links to the relevant sections.  Could you please approve the suggestion?  Will mark this thread as resolved.

2021-01-21 07:04 UTC, bcole approved these changes

2021-01-21 07:04 UTC, merged