Create REST vs GraphQL
IntuitDeveloper/intuit-api-docs pull request #7
Opened 2021-01-20 07:53 UTC by irajczi

Adding description to help those learn to transition from REST to GraphQL.

2021-01-20 19:05 UTC, bcole requested changes
Left some comments, and let's rename, perhaps:
`graphql-vs-rest.md`

2021-01-20 19:05 UTC, bcole commented on docs/faq/REST vs GraphQL
> +POST <graphBaseURL>/v1
```suggestion
POST `<graphBaseURL>/v1`
```

2021-01-20 19:05 UTC, bcole commented on docs/faq/REST vs GraphQL
> +TxnDate>'2020-01-18' and TxnDate<'2020-01-18'
```suggestion
`GET <baseUrl>/v3/company/<realmID>/query?query=select * from Invoice where 
TxnDate>'2020-01-18' and TxnDate<'2020-01-18' `
```

2021-01-20 19:05 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The above are only illustrative examples. To get a full list of operations and resources available in the Ecosystem API, use the introspection query or our API reference docs here. You can also refer
Just a comment, noticing the link here for Postman collections, since you pinged me about it @irajczi :
https://github.intuit.com/idg-dev-rel/GlobalEcosystem-API-Collections

Let me know if you find out if this is the correct one or not

2021-01-20 19:24 UTC, irajczi commented on docs/faq/REST vs GraphQL
> +nav_order: 1
Again sorry didn't realize order would change, we can make this number 1 and go into use cases later

2021-01-20 19:25 UTC, irajczi commented on docs/faq/REST vs GraphQL
> +In GraphQL, all requests are POSTs and the body of the request tells the server what needs to be done. All of the HTTP calls are made the same way and to the same endpoint but with different request
Oh yeah let's redirect here. Thanks for going over this in such detail. The external people won't have access to these docs anyway

2021-01-20 19:25 UTC, irajczi commented on docs/faq/REST vs GraphQL
> +In REST, schema updates may be notified to end-users via webhooks or release notes. GraphQL does this with the help of the [introspection query](https://docs.google.com/document/d/1F75QD_P4G7DHnNmzJR
How do I have it point to another page in this markup?

2021-01-20 19:34 UTC, irajczi commented on docs/faq/REST vs GraphQL
> +The above are only illustrative examples. To get a full list of operations and resources available in the Ecosystem API, use the introspection query or our API reference docs here. You can also refer
@nimisha84 do you know what Anil is sharing as the separate repository?

2021-01-20 23:48 UTC, bcole commented on docs/faq/REST vs GraphQL
> +In REST, schema updates may be notified to end-users via webhooks or release notes. GraphQL does this with the help of the [introspection query](https://docs.google.com/document/d/1F75QD_P4G7DHnNmzJR
```suggestion
In REST, schema updates may be notified to end-users via webhooks or release notes. GraphQL does this with the help of the [introspection query](../../graphql-concepts/introspection).
```
This should be the right way to do it.

2021-01-20 23:49 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the neces
```suggestion
The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the necessary information within the response body. Refer to [this section](../../graphql-concepts/error-handling-best-practices) for more details. (TODO - update section based on changes made for error responses)
```
Note - this depends on what you end up calling the file in the other PR but I think this should be it

2021-01-20 23:50 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the neces
Also I noticed that `TODO` - not sure if you want to do something else here or remove the TODO, before we go live.

2021-01-20 23:51 UTC, bcole commented on docs/faq/REST vs GraphQL
> +In GraphQL, all requests are POSTs and the body of the request tells the server what needs to be done. All of the HTTP calls are made the same way and to the same endpoint but with different request
```suggestion
In GraphQL, all requests are POSTs and the body of the request tells the server what needs to be done. All of the HTTP calls are made the same way and to the same endpoint but with different request bodies. To retrieve data, you would use a query operation, and to modify data you would use a mutation operation. More on those operations [here](../../graphql-concepts).
```

2021-01-20 23:54 UTC, bcole commented on docs/faq/REST vs GraphQL
> +nav_order: 1
Sure.  Just made that change in this PR.  Payroll FAQ is now number 2.

2021-01-21 07:07 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the neces
TODO comment here - not sure if you want to remove or do something here

2021-01-22 02:16 UTC, abisalehalliprasan commented on docs/faq/REST vs GraphQL
> +The above are only illustrative examples. To get a full list of operations and resources available in the Ecosystem API, use the introspection query or our API reference docs here. You can also refer
@irajczi @bcole : 

Here's the link to the private repo for `Retirement` collections: https://github.com/IntuitDeveloper/HelloWorld_GlobalEcosystemAPI_Samples_Collections/tree/master/Collections

2021-01-22 17:32 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The above are only illustrative examples. To get a full list of operations and resources available in the Ecosystem API, use the introspection query or our API reference docs here. You can also refer
```suggestion
The above are only illustrative examples. To get a full list of operations and resources available in the Ecosystem API, use the introspection query or our API reference docs here. You can also refer to our collections for Insomnia and Postman [here](https://github.com/IntuitDeveloper/HelloWorld_GlobalEcosystemAPI_Samples_Collections/tree/master/Collections). 
```

2021-01-23 00:02 UTC, bcole commented on docs/faq/REST vs GraphQL
> +The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the neces
```suggestion
The Ecosystem API handles errors differently. Errors related to the API gateway later will return status codes 4** or 5**, but API errors will return HTTP status code 200 and provide all of the necessary information within the response body. Refer to [this section](../../graphql-concepts/error-handling-best-practices) for more details.
```

2021-01-23 00:02 UTC, bcole approved these changes

2021-01-23 00:03 UTC, merged